model: densenet121
dataset: cifar100

epochs: 100
batch_size: 512
seed: 42

optimizer: SGD

schedulers: [none, cyclic, steplr, cosine]

clr_policies: [triangular, triangular2, exp_range]
clr_gamma: 0.99994
lr_bounds:
  - [0.1, 0.2]
  - [0.1, 0.3]
step_sizes: [4, 8]

fixed_lrs: [0.1, 0.2]

steplr_initial_lrs: [0.1, 0.05]
steplr_step_sizes: [30, 50]
steplr_gammas: [0.1, 0.2]

cosine_initial_lrs: [0.1, 0.05]
cosine_t_max: [100]
cosine_eta_min: [0.0, 0.001]
