model: densenet121
dataset: cifar100

epochs: 100
batch_size: 128
seed: 42

optimizer: SGD

schedulers: [none, cyclic]

clr_policies: [triangular, triangular2, exp_range]
lr_bounds:
  - [0.001, 0.01]
  - [0.001, 0.1]
step_sizes: [2, 4, 8]

fixed_lrs: [0.001, 0.01, 0.1]
